#!/usr/bin/env python3
"""
Train an emergency-intent text classifier (Tier 2: TF-IDF + logistic regression)
and export it to a self-contained C header (model.h) for on-device inference.

Pipeline:  text -> tokenize (unigrams+bigrams) -> TF-IDF -> logistic regression -> softmax

The tokenizer spec below is deliberately simple so it can be reproduced EXACTLY
in C. Any mismatch between this analyzer and the C tokenizer will silently hurt
accuracy, so keep them identical.
"""

import re
import sys
import numpy as np
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import cross_val_score

# ---- Tokenizer spec (MUST match classifier.c exactly) --------------------
# 1. lowercase (ASCII)
# 2. split into maximal runs of [a-z0-9]
# 3. drop tokens shorter than 2 chars
# 4. features = unigrams + adjacent bigrams (joined by a single space)
TOKEN_RE = re.compile(r"[a-z0-9]+")

def analyze(text):
    toks = [t for t in TOKEN_RE.findall(text.lower()) if len(t) >= 2]
    grams = list(toks)
    for i in range(len(toks) - 1):
        grams.append(toks[i] + " " + toks[i + 1])
    return grams
# --------------------------------------------------------------------------

CONF_THRESHOLD = 0.60   # below this, the C side reports "uncertain"

def main(csv_path="emergency_data.csv", out_path="model.h"):
    df = pd.read_csv(csv_path)
    texts = df["text"].astype(str).tolist()
    labels = df["label"].astype(str).tolist()

    vec = TfidfVectorizer(analyzer=analyze)      # smooth_idf=True, norm='l2' (defaults)
    X = vec.fit_transform(texts)

    clf = LogisticRegression(max_iter=2000, C=10.0)  # multinomial/softmax by default
    clf.fit(X, labels)

    # --- quick sanity: cross-validated accuracy -------------------------
    try:
        scores = cross_val_score(
            LogisticRegression(max_iter=2000, C=10.0), X, labels, cv=5
        )
        print(f"5-fold CV accuracy: {scores.mean():.3f} +/- {scores.std():.3f}")
    except Exception as e:
        print(f"(cv skipped: {e})")

    print(f"Train accuracy: {clf.score(X, labels):.3f}")
    print(f"Classes: {list(clf.classes_)}")
    print(f"Vocabulary size: {len(vec.vocabulary_)}")

    export_header(vec, clf, out_path)
    print(f"Wrote {out_path}")

def export_header(vec, clf, out_path):
    classes = list(clf.classes_)
    n_classes = len(classes)

    # vocabulary term -> column index, plus idf per column
    idf = vec.idf_
    # build (term, col, idf) sorted by term for binary search in C
    vocab_items = sorted(vec.vocabulary_.items(), key=lambda kv: kv[0])
    n_features = len(vocab_items)

    coef = clf.coef_            # shape (n_classes, n_features)
    intercept = clf.intercept_ # shape (n_classes,)
    # binary logistic edge case: sklearn stores a single row; expand to 2
    if coef.shape[0] == 1:
        coef = np.vstack([-coef[0], coef[0]])
        intercept = np.array([-intercept[0], intercept[0]])
        n_classes = 2

    def f(x):  # compact float literal
        return f"{x:.9g}f"

    lines = []
    lines.append("/* Auto-generated by train.py. Do not edit by hand. */")
    lines.append("#ifndef MODEL_H")
    lines.append("#define MODEL_H")
    lines.append("")
    lines.append(f"#define NUM_CLASSES {n_classes}")
    lines.append(f"#define NUM_FEATURES {n_features}")
    lines.append(f"#define CONF_THRESHOLD {CONF_THRESHOLD}f")
    lines.append("")
    names = ", ".join(f'"{c}"' for c in classes)
    lines.append(f"static const char *CLASS_NAMES[NUM_CLASSES] = {{ {names} }};")
    lines.append("")
    lines.append("typedef struct { const char *term; float idf; int col; } VocabEntry;")
    lines.append("static const VocabEntry VOCAB[NUM_FEATURES] = {")
    for term, col in vocab_items:
        safe = term.replace("\\", "\\\\").replace('"', '\\"')
        lines.append(f'  {{ "{safe}", {f(idf[col])}, {col} }},')
    lines.append("};")
    lines.append("")
    lines.append("static const float INTERCEPT[NUM_CLASSES] = {")
    lines.append("  " + ", ".join(f(b) for b in intercept))
    lines.append("};")
    lines.append("")
    lines.append("/* COEF[class][feature-column] */")
    lines.append("static const float COEF[NUM_CLASSES][NUM_FEATURES] = {")
    for r in range(n_classes):
        row = ", ".join(f(coef[r][c]) for c in range(n_features))
        lines.append(f"  {{ {row} }},")
    lines.append("};")
    lines.append("")
    lines.append("#endif /* MODEL_H */")

    with open(out_path, "w") as fh:
        fh.write("\n".join(lines) + "\n")

if __name__ == "__main__":
    args = sys.argv[1:]
    main(*args)
